### ISSUE TITLE
Make the Icon Larger

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#268]
I think it is because we are using the recommended icon size from the v1 VSIX format, but our icon on the new Visual Studio Marketplace is much smaller than most other extensions. Minor from a code perspective, but I think important from a professionalism perspective.

https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter

![image](https://cloud.githubusercontent.com/assets/493828/20329498/9d847dc0-ab66-11e6-9b13-a652cca8ff25.png)

![image](https://cloud.githubusercontent.com/assets/493828/20329509/ad65a304-ab66-11e6-8b7e-9159500d4b4c.png)
====================

Affected repos:

- [x] Framework
- [x] Console
- [x] nunit.xamarin (https://github.com/nunit/nunit.xamarin/issues/70)
- [x] nunit-vs-templates
- [ ] nunit.portable.agent
- [ ] dotnet-test-nunit
- [ ] nunit3-vs-adapter (In progress?)
- [ ] nunit-vs-adapter (Blocked: https://github.com/nunit/resources/issues/4)
- [ ] nunit-v2-framework-driver
- [ ] nunit-project-loader
- [ ] nunit-vs-testgenerator
- [ ] nunit-v2-result-writer
- [ ] vs-project-loader
- [ ] NUnit.System.Linq

External projects:
- [ ] teamcity-event-listener
- [ ] nunit3-tdnet-adapter

**Comment by CharliePoole** [comment]
We may need to keep this in multiple sizes.

**Comment by ChrisMaddock** [comment]
We actually have the same issue on NuGet gallery (for _almost_ all packages), and of course for all the other extensions. 

New icons for everyone! 😄

**Comment by rprouse** [comment]
>We may need to keep this in multiple sizes.

True, we will need to go back to VS 2012 and ensure whatever we use there continues to work. The screenshot above is for the 2012 version of Web Essentials, so I expect the larger icons are fine there too. The small icons are probably a hold back to the VSIX v1 format.

**Comment by CharliePoole** [comment]
What are we using for file explorer with the console?

**Comment by rprouse** [comment]
The console uses an ICO with large size icons embedded in it. I think the NuGet and VSIX require large PNG files, but I need to check.

**Comment by rprouse** [comment]
I downloaded several popular extensions that look good in Visual Studio and in the marketplace to check their icon sizes. A couple were 64x64, WebEssentials was 90x90 and one was 250x250.

**Comment by ChrisMaddock** [comment]
For NuGet - the biggest 'displayed' icon is 128x128 in the gallery, the recommendation seemed to be 256x256, for high dpi screens. There's open requests for ico/multiple file size support, nothing implemented yet however.

**Comment by ChrisMaddock** [comment]
@CharliePoole raised the issue over on https://github.com/nunit/nunit.xamarin/issues/70 of where the icons should actually live. It seems sensible to use github's hosting over nunit.org. Should we follow Cake's example and create a 'graphics' repo?

With the intention of being vaguely organised, here's a checklist of where we need to update. Once we decide what we're going for, we could create issues/move this list.

- [ ] Framework
- [ ] Console
- [ ] nunit.xamarin (https://github.com/nunit/nunit.xamarin/issues/70)
- [ ] nunit-vs-templates (https://github.com/nunit/nunit-vs-templates/issues/27)
- [ ] portable agent (Already uses a 256x256 icon, only if we decide on a change)
- [ ] dotnet-test-nunit (Already uses a 256x256 icon, only if we decide on a change)
- [ ] nunit-project-loader
- [ ] nunit3-vs-adapter - VSIX & NuGet - (https://github.com/nunit/nunit3-vs-adapter/issues/268) 
- [ ] teamcity-event-listener
- [ ] nunit-vs-adapter - VSIX & NuGet
- [ ] nunit-vs-testgenerator
- [ ] nunit-v2-framework-driver
- [ ] nunit3-tdnet-adapter ? (Cc @jcansdale)
- [ ] nunit-v2-result-writer
- [ ] vs-project-loader
- [ ] NUnit.System.Linq

Phew - there's a few to do! For the record, that list is excluding SL & CF.

**Comment by ChrisMaddock** [comment]
On VSIX's, the spec currently specifies a 32x32 icon, and 200x200 'preview image'. ([link](https://msdn.microsoft.com/en-us/library/hh696828.aspx)) That matches up with the biggest you found @rprouse.  I don't know if they're intending anything different with VSIX v3, but it would seem odd as they've just redone the 'marketplace'.

So, for the sake of making a decision, how about 32 and 200 for the VSIX's and 256 for the NuGet packages? And housing them in a new `/graphics/` repo, as we don't have any particular natural home for them? 😄

**Comment by CharliePoole** [comment]
Do we want to put anything here other than graphics? Text perhaps? In that case, maybe "resources." But "graphics" is ok by me as well.

**Comment by ChrisMaddock** [comment]
'resources' sounds sensible to me!

**Comment by CharliePoole** [comment]
The td.net adapter and the teamcity extension don't belong to us and probably shouldn't get our icon. I think that how we ultimately want to deal with these is something for the core team to decide so it's probably best not to spend time on them till that happens - unless there's a pressing need that is.

**Comment by rprouse** [comment]
> On VSIX's, the spec currently specifies a 32x32 icon

The docs haven't been updated, but in there was a fair amount of talk in the VSIX Gitter group. The icons on the marketplace are much bigger than 32x32, but if we have a 32x32 icon, it will not get scaled up. It will get scaled down in Visual Studio though. Most people recommend going with a multiple of 32 so that the scaling is cleaner and most people use a 64x64 icon, but as I've said, I've also seen 90x and 200x. I think we should go with the 64x for our VSIX packages.

The 200x200 preview image is the image of the extension running that appears in the details pane on the right in Visual Studio. We shouldn't change that. It is no longer used in the marketplace and I think it is dropped in VS 2017 too.

I have many icon sizes since I created them in the first place. I can upload here or to a repo. Rather than create yet another repo, should we use the docs repo to contain collateral like this?

**Comment by CharliePoole** [comment]
In some other thread, @ChrisMaddock and I were talking about putting images in a separate repo in the way that the Cake folks do it. I suggested the name resources as a bit more general than images.

**Comment by rprouse** [comment]
@CharliePoole name the repo and I can create/populate it. I have everything in dropbox now. I can create a resources folder with targeted icons and another folder with a variety of sizes that I have produced for other uses.

**Comment by CharliePoole** [comment]
My thought was "resources" or nunit-resources if you prefer. I figured we might have some text resources as well. You could structure it with folders or leave it flat.

**Comment by ChrisMaddock** [comment]
> The 200x200 preview image is the image of the extension...

Ah cool, I didn't know that! Sounds good, thank Rob!

**Comment by ChrisMaddock** [comment]
@rprouse - Do you think we could get this in for 3.6? If you can set the repo up, I'm happy to update the nuspecs. 😄

**Comment by CharliePoole** [comment]
@rprouse Were you planning on doing the adapter release? (Asking because of @ChrisMaddock 's question to you)

**Comment by ChrisMaddock** [comment]
Sorry - I meant the 3.6 console/framework. Forgot this issue was in the adapter repo. 😄

**Comment by rprouse** [comment]
@ChrisMaddock I have created the repo https://github.com/nunit/resources and uploaded the icons and logos to it.

**Comment by ChrisMaddock** [comment]
Great, thanks! Will update the nuspecs after Christmas - have a good one!

**Comment by CharliePoole** [comment]
Currently, the vsix embeds the icon while the nuspec uses a url. If vsix supports using a url, maybe we should consider doing that? Does anyone know?

**Comment by OsirisTerje** [comment]
From https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference  ,  <Icon> - This optional element is a relative path to an image file (png, bmp, jpeg, ico) contained in the package. The icon image should be 32x32 pixels (or will be shrunk to that size) and appears in the listview UI. If no Icon element is specified, the UI uses a default.   No change to this in 3.0 afaik

**Comment by CharliePoole** [comment]
I guess we leave it as is then? WRT size, however, it seems the docs don't reflect reality.

**Comment by OsirisTerje** [comment]
Since we don't have the url option, and we add icons to a separate repo, should we 1) copy the icons to where we want to use them, thus making duplicates, or 2) add the icons to an (internal) nuget package to be consumed by the project ?

**Comment by CharliePoole** [comment]
It only applies to vsixes, which are in the minority, so I'd be inclined to copy them. @ChrisMaddock @rprouse What do you think?

**Comment by CharliePoole** [comment]
Also, it should be pointed out that we are already copying them, so this wouldn't be a change.

**Comment by OsirisTerje** [comment]
I asked the PG, and got answer back that 90x90 is recommended icon size for the marketplace.

**Comment by CharliePoole** [comment]
I was going on the research @rprouse and @ChrisMaddock did. What do you say guys?

**Comment by rprouse** [comment]
I say copy the icons in as needed. Wherever URL's are available, link to the raw version in GitHub.

For size, when I checked other popular and well displayed VSIX files, 64x64 was popular, but so was 90x90. It seems to be getting larger over time, so I say go for the larger.

@ChrisMaddock I didn't add a 90x90 icon. The best way to produce them is using Inkscape and the SVG files. I also added a PDN for Paint.NET, but the SVG files are higher quality. If you want me to do it, just shout.

**Comment by ChrisMaddock** [comment]
Thanks @rprouse @OsirisTerje, I'll create a 90x90. :-) 

Agreed that pulling the icons from an online source would be nicer than copying, but with 16 repo's to update, I'm tempted to take the easy route out, and just copy them as they currently are. Maybe something to consider for any new projects?

**Comment by CharliePoole** [comment]
I didn't realize you planned to do this across all projects. Please watch out for conflicts. For example, there's already a branch of the adapter that points to the resources repo.

**Comment by ChrisMaddock** [comment]
@CharliePoole - I did, but more than happy for anyone else to update things as well! 😄 

There's a checklist a few posts up - perhaps we can use that to keep track. I can then just make sure everything is covered before the next round of releases.

https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-263020854

**Comment by CharliePoole** [comment]
@ChrisMaddock Right, I saw the checklist, but I didn't realize it meant you would be doing all of them from this issue about the nunit3 adapter. No problem with it if you take the extra step of looking at the PRs that are already under way for each project before doing it. FWIW, we're already in the next round of releases. 😄

**Comment by CharliePoole** [comment]
To summarize what (I think) is the agreement - out of all those comments above - we want to use:
* A copy of the 90x90 icon for the vsix
* A link to the 256x256 icon for nuget packages where possible, but a copy if it's more expeditious to do that. My thinking is that you should do the link if you have to edit the nuspec anyway to change the file name.

Regarding where to link... I'll write something for the resources/readme.md after I have a chance to actually try the different alternatives and see them work.

**Comment by ChrisMaddock** [comment]
Those are the same conclusions I had drawn, from everything so far! 😄

**Comment by ChrisMaddock** [comment]
I've done a few nuspecs and a vsix. Will hold off until those have been merged for now - save having to redo the whole lot if there's something wrong. 😄

> For example, there's already a branch of the adapter that points to the resources repo.

@CharliePoole - I can't see this, is it perhaps a local branch? Shall I leave this repo to you?

**Comment by CharliePoole** [comment]
It is local... I'll go ahead and push it. I guess we need better ways to coordinate cross-cutting changes. 😞

**Comment by CharliePoole** [comment]
Pushed. Turns out it didn't have other changes - I was thinking of the Project editor package.

**Comment by ChrisMaddock** [comment]
PRs for this should all now be done. 😄 

> The td.net adapter and the teamcity extension don't belong to us and probably shouldn't get our icon. I think that how we ultimately want to deal with these is something for the core team to decide so it's probably best not to spend time on them till that happens - unless there's a pressing need that is.

Based on this, I haven't updated the those two repo's. I also didn't touch any of the old projects (CF/SL) - hopefully they won't be necessary.
